# development
version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - .env.app
    volumes:
      - .:/home/app/webapp
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command:
      - rails s

  mysql:
    image: mysql:5.7.19
    env_file:
      - .env.mysql
    volumes:
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
      - "./db/conf.d:/etc/mysql/conf.d"
      - "./db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
