version: '2'
services:
  web:
    build:
      context: .
    env_file:
      - .env.docker
    volumes:
      - .:/home/app/webapp
    environment:
      RAILS_ENV: development
      PASSENGER_APP_ENV: development
    ports:
      - "3000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=chiselmetimbers
    volumes:
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
      - "./db/conf.d:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
